encryptionsalt: v1:bqmx/68vrK8=:v1:vZ0uN+VQMQ4zPAuX:OocHAeHndZuC4ZJgT98F+q6iHV5wAA==
config:
  # Public env vars
  dms:PUBLIC_WEB_DOMAIN: localhost
  dms:PUBLIC_WEB_PORT: "3000"
  dms:PUBLIC_WEB_SSL: "false"
  # Secrets (encrypt with `pulumi config set --secret <key> <value>`)
  dms:AUTH_SECRET: dms-v1-dev-secret-change-in-production-32chars
  dms:DB_HOST: localhost
  dms:DB_PASSWORD: dms_password
  dms:DB_PORT: "5432"
  dms:DB_SSL: "false"
  dms:DB_USER: dms
  dms:STORAGE_ACCESS_KEY: dms
  dms:STORAGE_BUCKET: dms-platform
  dms:STORAGE_ENDPOINT: http://localhost:8333
  dms:STORAGE_FORCE_PATH_STYLE: "true"
  dms:STORAGE_REGION: us-east-1
  dms:STORAGE_SECRET_KEY: dms_password
